### ISSUE TITLE
No int causing compiling issue

### ISSUE THREAD

**Issue by hwangs12** [tridibsamanta/CPP_Beginner_to_Expert#3]
Hi @tridibsamanta, thanks for writing this repo. 
I cloned your repo to learn CPP but they don't start with **int main** but just **main**.
Is this how new compilers accept CPP code these days or is this a typo?
Would appreciate your clarification
Regards,

**Comment by Karansemwal** [comment]
yes its incorrect code where it is `main` in some examples, it must be `int main()`

**Comment by MichaeINeumann** [comment]
Hi hwangs12, I think you are right.
I learned that all C++ programs must have a main function that returns an int value.
Return 0 to execute the program normally.

I added that and created a PR.

**Comment by swarupsahu08** [comment]
Hello @hwangs12 You are correct that the programs are not executable as there is no int main() in the code base and needs to return 0 at last to run the program smoothly and can you assign me this issue so that I can make the relevant changes to the code

**Comment by hwangs12** [comment]
@MichaeINeumann @swarupsahu08  I approved Michael's PR. I will close the issue. Thanks.
